
 PARAMETER VERSION = 2.2.0


BEGIN OS
 PARAMETER OS_NAME = standalone
 PARAMETER OS_VER = 3.08.a
 PARAMETER PROC_INSTANCE = microblaze_0
 PARAMETER STDIN = usb_uart
 PARAMETER STDOUT = usb_uart
END


BEGIN PROCESSOR
 PARAMETER DRIVER_NAME = cpu
 PARAMETER DRIVER_VER = 1.14.a
 PARAMETER HW_INSTANCE = microblaze_0
END


BEGIN DRIVER
 PARAMETER DRIVER_NAME = bram
 PARAMETER DRIVER_VER = 3.01.a
 PARAMETER HW_INSTANCE = axi_bram_0
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = axicdma
 PARAMETER DRIVER_VER = 2.01.a
 PARAMETER HW_INSTANCE = axi_cdma_0
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = gpio
 PARAMETER DRIVER_VER = 3.00.a
 PARAMETER HW_INSTANCE = axi_gpio_0
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = sysmon
 PARAMETER DRIVER_VER = 5.02.a
 PARAMETER HW_INSTANCE = axi_sysmon_adc_0
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = tmrctr
 PARAMETER DRIVER_VER = 2.04.a
 PARAMETER HW_INSTANCE = axi_timer_0
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = uartlite
 PARAMETER DRIVER_VER = 2.00.a
 PARAMETER HW_INSTANCE = debug_module
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = llfifo
 PARAMETER DRIVER_VER = 2.03.a
 PARAMETER HW_INSTANCE = eth_a_fifo
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = axiethernet
 PARAMETER DRIVER_VER = 3.00.a
 PARAMETER HW_INSTANCE = eth_a_mac
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = llfifo
 PARAMETER DRIVER_VER = 2.03.a
 PARAMETER HW_INSTANCE = eth_b_fifo
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = axiethernet
 PARAMETER DRIVER_VER = 3.00.a
 PARAMETER HW_INSTANCE = eth_b_mac
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = bram
 PARAMETER DRIVER_VER = 3.01.a
 PARAMETER HW_INSTANCE = microblaze_0_d_bram_ctrl
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = bram
 PARAMETER DRIVER_VER = 3.01.a
 PARAMETER HW_INSTANCE = microblaze_0_i_bram_ctrl
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = radio_controller_axi
 PARAMETER DRIVER_VER = 3.00.d
 PARAMETER HW_INSTANCE = radio_controller_0
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = uartlite
 PARAMETER DRIVER_VER = 2.00.a
 PARAMETER HW_INSTANCE = usb_uart
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = w3_ad_controller_axi
 PARAMETER DRIVER_VER = 3.01.a
 PARAMETER HW_INSTANCE = w3_ad_controller_0
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = w3_clock_controller_axi
 PARAMETER DRIVER_VER = 3.01.a
 PARAMETER HW_INSTANCE = w3_clock_controller_0
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = w3_iic_eeprom_axi
 PARAMETER DRIVER_VER = 1.00.b
 PARAMETER HW_INSTANCE = w3_iic_eeprom_onboard
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = w3_userio_axi
 PARAMETER DRIVER_VER = 1.00.a
 PARAMETER HW_INSTANCE = w3_userio
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = w3_warplab_agc_axiw
 PARAMETER DRIVER_VER = 2.00.b
 PARAMETER HW_INSTANCE = warplab_agc
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = w3_warplab_buffers_axiw
 PARAMETER DRIVER_VER = 2.02.b
 PARAMETER HW_INSTANCE = warplab_buffers
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = w3_warplab_trigger_proc_axiw
 PARAMETER DRIVER_VER = 1.01.a
 PARAMETER HW_INSTANCE = warplab_trigger_proc
END


BEGIN LIBRARY
 PARAMETER LIBRARY_NAME = WARP_HW_VER
 PARAMETER LIBRARY_VER = 3.10.a
 PARAMETER PROC_INSTANCE = microblaze_0
END

BEGIN LIBRARY
 PARAMETER LIBRARY_NAME = WARPxilnet
 PARAMETER LIBRARY_VER = 3.01.a
 PARAMETER PROC_INSTANCE = microblaze_0
 PARAMETER EMAC_INSTNAME = eth_a_mac
END

